/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CadastroController;
import controller.Conexao;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import model.CadastroModel;
import model.TabelaCadastroModel;


/**
 *
 * @author JeffersonAndrade
 */
public class TelaInicioCadastro extends javax.swing.JFrame {
    
    Conexao con = new Conexao();
    CadastroModel mod = new CadastroModel();
    CadastroController control = new CadastroController ();
    private TelaLoginView TelaLogin;


    /**
     * Creates new form TelaInicioCadastro
     */
    public TelaInicioCadastro() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        preencherTabela("SELECT *from cadastro order by data_viagem");
        setTitle("SysCadastro - Leticia Turismo");
        Contador();
        setIcon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCadastro = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btFiltrar = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtPesquisa = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btExcluir1 = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbContador = new javax.swing.JLabel();
        txtContador = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNovo = new javax.swing.JMenuItem();
        jMenuItemImprimir = new javax.swing.JMenuItem();
        MenuPesquisar = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        MenuNovo = new javax.swing.JMenu();
        MenuContatos = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SysCadastro - Leticia Turismo");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tableCadastro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Título 5", "Título 6", "Título 7", "Título 8", "Título 9"
            }
        ));
        tableCadastro.setRowHeight(30);
        tableCadastro.setRowMargin(5);
        tableCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCadastroMouseClicked(evt);
            }
        });
        tableCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableCadastroKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableCadastro);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Todas as reservas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PLATAFORMA DE GERENCIAMENTO DE RESERVAS | ONLINE");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SysCadastro © - Leticia Turismo - (v.4.0 | 2021) 04/2019 por Jefferson Andrade");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel16.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel16MouseMoved(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo LP (1).png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btFiltrar.setBackground(new java.awt.Color(0, 0, 255));
        btFiltrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        btFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filtro.png"))); // NOI18N
        btFiltrar.setText("Filtrar");
        btFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltrarActionPerformed(evt);
            }
        });

        jDateChooser2.setDateFormatString("dd-MM-yyyy");

        jLabel3.setText("Até");

        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jLabel4.setText("FiILTRAR POR DATA:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btFiltrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFiltrar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btPesquisar.setBackground(new java.awt.Color(0, 0, 255));
        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btPesquisarMouseMoved(evt);
            }
        });
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        btPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btPesquisarKeyPressed(evt);
            }
        });

        jLabel5.setText("Pesquisar por nome");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btPesquisar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btExcluir1.setBackground(new java.awt.Color(0, 0, 255));
        btExcluir1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btExcluir1.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novo.png"))); // NOI18N
        btExcluir1.setText("NOVO");
        btExcluir1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btExcluir1MouseMoved(evt);
            }
        });
        btExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluir1ActionPerformed(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(0, 0, 255));
        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        btExcluir.setText("EXCLUIR");
        btExcluir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btExcluirMouseMoved(evt);
            }
        });
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btImprimir.setBackground(new java.awt.Color(0, 0, 255));
        btImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        btImprimir.setText("Imprimir");
        btImprimir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btImprimirMouseMoved(evt);
            }
        });
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btImprimir)
                .addGap(18, 18, 18)
                .addComponent(btExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExcluir1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btImprimir)
                    .addComponent(btExcluir)
                    .addComponent(btExcluir1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbContador.setBackground(new java.awt.Color(255, 255, 255));
        lbContador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbContador.setForeground(new java.awt.Color(255, 255, 255));
        lbContador.setText("Qt. registros");

        txtContador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtContador.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbContador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbContador)
                    .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(155, 155, 155))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu1.setText("Arquivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItemNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNovo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItemNovo.setText("Novo");
        jMenuItemNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNovo);

        jMenuItemImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemImprimir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItemImprimir.setText("Imprimir");
        jMenuItemImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImprimirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemImprimir);

        MenuPesquisar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        MenuPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        MenuPesquisar.setText("Pesquisar");
        MenuPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPesquisarActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPesquisar);

        jMenuItemSair.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        MenuNovo.setText("Novo");
        MenuNovo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuNovoMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuNovo);

        MenuContatos.setText("Contatos");
        MenuContatos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuContatosMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuContatos);

        jMenu2.setText("Ferramentas");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem1.setText("Apagar tudo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        mod.setPesquisa(btPesquisar.getText());

        CadastroModel model = control.buscaUsuario(mod);

        preencherTabela("SELECT *FROM cadastro WHERE nome like '%"+txtPesquisa.getText() +"%' order by data_viagem");
        Contador();
        
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        control.delete(mod);
        mod.setId(null);
        
        preencherTabela("SELECT *FROM cadastro order by data_viagem");
        Contador();
        
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        try{
        MessageFormat headerFormat = new MessageFormat("Registros de reserva de passageiros");
        MessageFormat footerFormat = new MessageFormat("SysCadastro © 04/2019 - Leticia Turismo");
        
        tableCadastro.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
        }catch (PrinterException e){
        Logger.getLogger(TelaInicioCadastro.class.getName()).log
        (Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btImprimirActionPerformed

    private void tableCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCadastroMouseClicked
        
        try {
            
            TabelaCadastroModel modelo = (TabelaCadastroModel)tableCadastro.getModel();
            int seectedRow = tableCadastro.getSelectedRow();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)modelo.getValueAt(seectedRow, 9).toString());
            jDateChooser1.setDate(date);
         
        if(evt.getClickCount() >1 ){
            
            int row = this.tableCadastro.rowAtPoint(evt.getPoint());
            
            Object obj = (tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 0));
            String id = obj.toString();

            Object obj1 = (tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 1));
            String quant = obj1.toString();
            
            Object obj2 = (tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 2));
            String nome = obj2.toString();

            Object obj3 = (tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 3));
            String telefone = obj3.toString();

            Object obj4 = (tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 4));
            String embarque = obj4.toString();

            Object obj5 = (tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 5));
            String destino = obj5.toString();

            Object obj6 = (tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 6));
            String status = obj6.toString();
            
            Object obj7 = (tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 7));
            String valor = obj7.toString();
            
            Object obj8 = (tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 8));
            String valortotal = obj8.toString();
            
            /*Object obj9 = (tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 9));
            String date = obj9.toString();*/
            
            TelaAterarCadastroView tela1 = new TelaAterarCadastroView();

            tela1.setTextfild1(this, id);
            tela1.setId(this, id);
            tela1.setTextfild2(this, quant);
            tela1.setTextfild3(this, nome);
            tela1.setTextfild4(this, telefone);
            tela1.setTextfild5(this, embarque);
            tela1.setTextfild6(this, destino);
            tela1.setTextfild7(this, status);
            tela1.setTextfild8(this, valor);
            tela1.setTextfild9(this, valortotal);
            tela1.jDateChooser1(this, date);
            

            tela1.setVisible(true);
            dispose();
                    
        }else{
            String id = (String) tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 0);
            con.conectar();
            con.executeSql("SELECT * FROM cadastro WHERE id="+id);
            try {
                con.rs.first();
                mod.setId(con.rs.getInt("id"));
            } catch (SQLException ex) {

            }

        }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "NÃO É POSSIVEL SELECIONAR CAMPO VAZIO, ALTERE O ITEM VAZIO NO BANCO DE DADOS!");
        }
        
    }//GEN-LAST:event_tableCadastroMouseClicked

    private void tableCadastroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableCadastroKeyReleased
        
        String id = (String) tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 0);
        System.out.println(id);
        con.conectar();
        con.executeSql("SELECT * FROM cadastro WHERE id="+id);
        try{
            con.rs.first();
            mod.setId(con.rs.getInt("id"));

        } catch(SQLException exception) {
            System.out.println(exception.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao selecionar");
        }

        con.desconectarBanco();

    }//GEN-LAST:event_tableCadastroKeyReleased

    private void MenuNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuNovoMouseClicked
        TelaNovoCadastroView tela = new TelaNovoCadastroView();
        tela.setVisible(true);
        dispose();

    }//GEN-LAST:event_MenuNovoMouseClicked

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        TelaLoginView tela1 = new TelaLoginView();
        tela1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImprimirActionPerformed
        try{
            MessageFormat headerFormat = new MessageFormat("Registros de reserva de passageiros");
            MessageFormat footerFormat  = new MessageFormat("SysCadastro © 04/2019 - Leticia Turismo");
            

            tableCadastro.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
        }catch (PrinterException e){
            Logger.getLogger(TelaInicioCadastro.class.getName()).log
            (Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jMenuItemImprimirActionPerformed

    private void jMenuItemNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoActionPerformed
        TelaNovoCadastroView tela = new TelaNovoCadastroView();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemNovoActionPerformed

    private void MenuPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPesquisarActionPerformed
        txtPesquisa.grabFocus();
    }//GEN-LAST:event_MenuPesquisarActionPerformed

    private void btPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btPesquisarKeyPressed
            btPesquisar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    btPesquisar.doClick();
                }
            }
        });        
    }//GEN-LAST:event_btPesquisarKeyPressed

    private void MenuContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuContatosMouseClicked
        // TODO add your handling code here:
        TelaContatos tela = new TelaContatos();
        tela.setVisible(true);
    }//GEN-LAST:event_MenuContatosMouseClicked

    private void btFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltrarActionPerformed
    mod.setPesquisa(btFiltrar.getText());

        CadastroModel model = control.filtrarRegistro(mod);
        DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        preencherTabela("SELECT *FROM cadastro WHERE data_viagem>= '"+df.format(jDateChooser1.getDate())+"' and data_viagem<= '"+df.format(jDateChooser2.getDate())+"' order by data_viagem");
        Contador();
    }//GEN-LAST:event_btFiltrarActionPerformed

    private void btExcluirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMouseMoved
    btExcluir.setToolTipText("Excluir registro selecionado");        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirMouseMoved

    private void btPesquisarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPesquisarMouseMoved
    btPesquisar.setToolTipText("Pesquisar por nome");        // TODO add your handling code here:
    }//GEN-LAST:event_btPesquisarMouseMoved

    private void jLabel16MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseMoved
    jLabel16.setToolTipText("SysCadastro © desenvolvido por Jefferson Andrade, 04/2019 para a empresa Leticia Turismo");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseMoved

    private void btImprimirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImprimirMouseMoved
    btImprimir.setToolTipText("Imprime toda a lista ou apenas uma consulta");        // TODO add your handling code here:
    }//GEN-LAST:event_btImprimirMouseMoved

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_F5) {
                    preencherTabela("SELECT *FROM cadastro order by data_viagem");
                    Contador();
                }
            }
        }); 
    }//GEN-LAST:event_formKeyPressed

    private void btExcluir1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluir1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluir1MouseMoved

    private void btExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluir1ActionPerformed
        TelaNovoCadastroView tela = new TelaNovoCadastroView();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btExcluir1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        control.delete_all(mod);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public void preencherTabela(String Sql){
        
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"id","quant","nome","telefone","cidade_origem","cidade_destino",
            "status","valorpg","valortotal","data_viagem"};
        con.conectar();
        con.executeSql(Sql);
        try{
            con.rs.first();
            do{
                dados.add(new Object[]{con.rs.getString("id"),con.rs.getString("quant"),con.rs.getString("nome"),
                    con.rs.getString("telefone"),con.rs.getString("cidade_origem"),con.rs.getString("cidade_destino"),
                    con.rs.getString("status"),con.rs.getBigDecimal("valorpg"),con.rs.getBigDecimal("valortotal"),
                    con.rs.getDate("data_viagem")});
            }while(con.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Nenhum registro encontrado!");
            txtPesquisa.setText("");
        }
    TabelaCadastroModel modelo = new TabelaCadastroModel(dados, colunas);
    tableCadastro.setModel(modelo);
    
    DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
    
    tableCadastro.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    tableCadastro.getColumnModel().getColumn(0).setMaxWidth(50);
    tableCadastro.getColumnModel().getColumn(1).setMaxWidth(50);
    tableCadastro.getColumnModel().getColumn(2).setMaxWidth(550);
    tableCadastro.getColumnModel().getColumn(3).setMaxWidth(200);
    tableCadastro.getColumnModel().getColumn(4).setMaxWidth(240);
    tableCadastro.getColumnModel().getColumn(5).setMaxWidth(250);
    tableCadastro.getColumnModel().getColumn(6).setMaxWidth(140);
    tableCadastro.getColumnModel().getColumn(7).setMaxWidth(130);
    tableCadastro.getColumnModel().getColumn(8).setMaxWidth(130);
    tableCadastro.getColumnModel().getColumn(9).setMaxWidth(150);
    
    
    //tableCadastro.setFont(new Font("Default",Font.PLAIN, 14));
    tableCadastro.getTableHeader().setReorderingAllowed(true);
    tableCadastro.setAutoCreateRowSorter(true); 
    tableCadastro.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    con.desconectarBanco();
    
}
     
    private void Contador() {
        
        int somaTotal=0;
        for (int i=0; i<tableCadastro.getRowCount(); i++)
          somaTotal+=Double.parseDouble(tableCadastro.getValueAt(i, 1).toString());
        txtContador.setText(" "+somaTotal);
        
}
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LP_icon.png")));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaInicioCadastro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuContatos;
    private javax.swing.JMenu MenuNovo;
    private javax.swing.JMenuItem MenuPesquisar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btExcluir1;
    private javax.swing.JButton btExcluir2;
    private javax.swing.JButton btExcluir3;
    private javax.swing.JButton btFiltrar;
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btImprimir1;
    private javax.swing.JButton btPesquisar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemImprimir;
    private javax.swing.JMenuItem jMenuItemNovo;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbContador;
    private javax.swing.JTable tableCadastro;
    private javax.swing.JLabel txtContador;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}