/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teste;

import controller.Conexao;
import controller.CadastroController;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import model.CadastroModel;
import model.TabelaCadastroModel;

/**
 *
 * @author user
 */
public class TelaCadastroViewCopia extends javax.swing.JFrame {
    
    Conexao con = new Conexao();
    CadastroModel mod = new CadastroModel();
    CadastroController control = new CadastroController ();
 
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastroViewCopia() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        preencherTabela("SELECT *FROM cadastro order by Id");
        setTitle("SysCadastro - C&N Turismo");
        Contador();
        setIcon();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btImprimir = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCidade_origem = new javax.swing.JTextField();
        btNovo = new javax.swing.JButton();
        txtTelefone = new javax.swing.JFormattedTextField();
        btExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btEditar = new javax.swing.JButton();
        txtCidade_destino = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCadastro = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        lbContador = new javax.swing.JLabel();
        txtContador = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        bt_limpar_tabela = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Reserva de passagens");

        jLabel15.setText("SysCadastro © - C&N Turismo - (v.1.1) 04/2019 por Jefferson Andrade");

        btImprimir.setBackground(new java.awt.Color(0, 0, 255));
        btImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        btImprimir.setText("Imprimir");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Nova reserva - insira os dados");

        btSalvar.setBackground(new java.awt.Color(0, 0, 255));
        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        btSalvar.setText("SALVAR");
        btSalvar.setBorderPainted(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jLabel4.setText("EMBARQUE");

        txtCidade_origem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidade_origemActionPerformed(evt);
            }
        });

        btNovo.setBackground(new java.awt.Color(0, 0, 255));
        btNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNovo.setForeground(new java.awt.Color(255, 255, 255));
        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novo.png"))); // NOI18N
        btNovo.setText("NOVO");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btExcluir.setBackground(new java.awt.Color(0, 0, 255));
        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        btExcluir.setText("EXCLUIR");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jLabel3.setText("TELEFONE");

        jLabel6.setText("DATA");

        jLabel2.setText("NOME");

        jLabel5.setText("DESTINO");

        btEditar.setBackground(new java.awt.Color(0, 0, 255));
        btEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEditar.setForeground(new java.awt.Color(255, 255, 255));
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btEditar.setText("EDITAR");
        btEditar.setMaximumSize(new java.awt.Dimension(83, 23));
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Reservas cadastradas");

        tableCadastro.getTableHeader().setReorderingAllowed(false);
        tableCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCadastroMouseClicked(evt);
            }
        });
        tableCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableCadastroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableCadastroKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableCadastro);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Buscar reserva");

        lbContador.setText("Qt. registros");

        btPesquisar.setBackground(new java.awt.Color(0, 0, 255));
        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        bt_limpar_tabela.setBackground(new java.awt.Color(255, 51, 51));
        bt_limpar_tabela.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_limpar_tabela.setForeground(new java.awt.Color(255, 255, 255));
        bt_limpar_tabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        bt_limpar_tabela.setText("Apagar tudo");
        bt_limpar_tabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limpar_tabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCidade_destino, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCidade_origem, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNovo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btImprimir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btPesquisar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_limpar_tabela)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbContador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCidade_origem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCidade_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSalvar)
                            .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btExcluir)
                            .addComponent(btNovo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(bt_limpar_tabela))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbContador)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btImprimir)
                .addGap(52, 52, 52)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 12, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        mod.setPesquisa(btPesquisar.getText());

        CadastroModel model = control.buscaUsuario(mod);

        preencherTabela("SELECT *FROM cadastro WHERE nome like '%"+txtPesquisa.getText() +"%' order by id");
        Contador();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void tableCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCadastroMouseClicked
        // TODO add your handling code here:
        String id = (String) tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 0);
        System.out.println(id);
        con.conectar();
        con.executeSql("SELECT * FROM cadastro WHERE id="+id);
        try{
            con.rs.first();
            mod.setId(con.rs.getInt("id"));

            txtNome.setText(String.valueOf(con.rs.getString("nome")));
            txtTelefone.setText(String.valueOf(con.rs.getString("telefone")));
            txtCidade_origem.setText(String.valueOf(con.rs.getString("cidade_origem")));
            txtCidade_destino.setText(String.valueOf(con.rs.getString("cidade_destino")));
            txtData.setText(String.valueOf(con.rs.getString("data_viagem")));

        } catch(SQLException exception) {
            System.out.println(exception.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao selecionar");
        }

        con.desconectarBanco();

        txtNome.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtCidade_origem.setEnabled(false);
        txtCidade_destino.setEnabled(false);
        txtData.setEnabled(false);
        btEditar.setEnabled(true);
        btExcluir.setEnabled(true);
    }//GEN-LAST:event_tableCadastroMouseClicked

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        txtNome.setEnabled(true);
        txtTelefone.setEnabled(true);
        txtCidade_origem.setEnabled(true);
        txtCidade_destino.setEnabled(true);
        txtData.setEnabled(true);

        txtPesquisa.setText("");
        Contador();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
       
        control.delete(mod);
   
        btEditar.setEnabled(false);
        btExcluir.setEnabled(false);

        txtNome.setText("");
        txtTelefone.setText("");
        txtCidade_origem.setText("");
        txtCidade_destino.setText("");
        txtData.setText("");
        mod.setId(null);
        txtNome.grabFocus();

        preencherTabela("select * from cadastro order by id");
        Contador();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        btEditar.setEnabled(false);
        btExcluir.setEnabled(false);

        txtNome.setText("");
        txtTelefone.setText("");
        txtCidade_origem.setText("");
        txtCidade_destino.setText("");
        txtData.setText("");
        mod.setId(null);

        txtNome.setEnabled(true);
        txtTelefone.setEnabled(true);
        txtCidade_origem.setEnabled(true);
        txtCidade_destino.setEnabled(true);
        txtData.setEnabled(true);
        mod.setId(null);
        txtNome.grabFocus();

        Contador();
    }//GEN-LAST:event_btNovoActionPerformed

    private void txtCidade_origemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidade_origemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidade_origemActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        mod.setNome(txtNome.getText());
        mod.setTelefone(txtTelefone.getText());
        mod.setCidade_origem(txtCidade_origem.getText());
        mod.setCidade_destino(txtCidade_destino.getText());
        //mod.setData_viagem(txtData.getText());

        if (mod.getId() == null) {
            control.salvar(mod);
        } else {
            control.editar(mod);
        }
        preencherTabela("select * from cadastro order by id");
        Contador();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        try{
            MessageFormat headerFormat = new MessageFormat("Registros de reserva de passagens");
            MessageFormat footerFormat = new MessageFormat("SysCadastro © 04/2019 - C&N Turismo");

            tableCadastro.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
        }catch (PrinterException e){
            Logger.getLogger(TelaCadastroViewCopia.class.getName()).log
            (Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btImprimirActionPerformed

    private void tableCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableCadastroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableCadastroKeyPressed

    private void tableCadastroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableCadastroKeyReleased
        // TODO add your handling code here:
        String id = (String) tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 0);
        System.out.println(id);
        con.conectar();
        con.executeSql("SELECT * FROM cadastro WHERE id="+id);
        try{
            con.rs.first();
            mod.setId(con.rs.getInt("id"));

            txtNome.setText(String.valueOf(con.rs.getString("nome")));
            txtTelefone.setText(String.valueOf(con.rs.getString("telefone")));
            txtCidade_origem.setText(String.valueOf(con.rs.getString("cidade_origem")));
            txtCidade_destino.setText(String.valueOf(con.rs.getString("cidade_destino")));
            txtData.setText(String.valueOf(con.rs.getString("data_viagem")));

        } catch(SQLException exception) {
            System.out.println(exception.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao selecionar");
        }

        con.desconectarBanco();

        txtNome.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtCidade_origem.setEnabled(false);
        txtCidade_destino.setEnabled(false);
        txtData.setEnabled(false);
        btEditar.setEnabled(true);
        btExcluir.setEnabled(true);
    }//GEN-LAST:event_tableCadastroKeyReleased

    private void bt_limpar_tabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpar_tabelaActionPerformed
        // TODO add your handling code here:
        control.delete_all(mod);
        
    }//GEN-LAST:event_bt_limpar_tabelaActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"id","nome","telefone","cidade_origem","cidade_destino","data_viagem"};
        con.conectar();
        con.executeSql(Sql);
        try{
            con.rs.first();
            do{
                dados.add(new Object[]{con.rs.getString("id"),con.rs.getString("nome"),con.rs.getString("telefone"),con.rs.getString("cidade_origem"),con.rs.getString("cidade_destino"),con.rs.getString("data_viagem")});
            }while(con.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Registro não encontrado!");
        }
    TabelaCadastroModel modelo = new TabelaCadastroModel(dados, colunas);
    tableCadastro.setModel(modelo);
    
    tableCadastro.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    tableCadastro.getColumnModel().getColumn(0).setMaxWidth(40);
    tableCadastro.getColumnModel().getColumn(1).setMaxWidth(350);
    tableCadastro.getColumnModel().getColumn(2).setMaxWidth(120);
    tableCadastro.getColumnModel().getColumn(3).setMaxWidth(160);
    tableCadastro.getColumnModel().getColumn(4).setMaxWidth(160);
    tableCadastro.getColumnModel().getColumn(5).setMaxWidth(100);
    
    tableCadastro.getTableHeader().setReorderingAllowed(true);
    tableCadastro.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    con.desconectarBanco();
    
    }
    
    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroViewCopia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroViewCopia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroViewCopia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroViewCopia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroViewCopia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton bt_limpar_tabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbContador;
    private javax.swing.JTable tableCadastro;
    private javax.swing.JTextField txtCidade_destino;
    private javax.swing.JTextField txtCidade_origem;
    private javax.swing.JLabel txtContador;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void Contador() {
        
        int filas=tableCadastro.getRowCount();
        txtContador.setText(" " + filas);
        
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("CN logo.png")));
    } 
}