/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teste;

import controller.Conexao;
import controller.CadastroController;
import java.awt.Toolkit;
import java.awt.font.TextAttribute;
import java.awt.print.PrinterException;
import static java.nio.file.Files.delete;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import model.CadastroModel;
import model.TabelaCadastroModel;
import view.TelaAterarCadastroView;
import view.TelaNovoCadastroView;


/**
 *
 * @author user
 */
public class TelaCadastroInicioViewCopia2 extends javax.swing.JFrame {
    
    Conexao con = new Conexao();
    CadastroModel mod = new CadastroModel();
    CadastroController control = new CadastroController ();
 
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastroInicioViewCopia2() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        preencherTabela("SELECT *FROM cadastro order by Id");
        setTitle("SysCadastro - C&N Turismo");
        Contador();
        setIcon();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btImprimir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCadastro = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        lbContador = new javax.swing.JLabel();
        txtContador = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        bt_limpar_tabela = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArquivo = new javax.swing.JMenu();
        MenuNovo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Todas as reservas");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("SysCadastro © - C&N Turismo - (v.1.1) 04/2019 por Jefferson Andrade");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btImprimir.setBackground(new java.awt.Color(0, 0, 255));
        btImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        btImprimir.setText("Imprimir");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Reservas cadastradas");

        tableCadastro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableCadastro.getTableHeader().setReorderingAllowed(false);
        tableCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCadastroMouseClicked(evt);
            }
        });
        tableCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableCadastroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableCadastroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tableCadastroKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tableCadastro);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Buscar reserva");

        lbContador.setText("Qt. registros");

        btPesquisar.setBackground(new java.awt.Color(0, 0, 255));
        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        bt_limpar_tabela.setBackground(new java.awt.Color(255, 51, 51));
        bt_limpar_tabela.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_limpar_tabela.setForeground(new java.awt.Color(255, 255, 255));
        bt_limpar_tabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        bt_limpar_tabela.setText("Apagar tudo");
        bt_limpar_tabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limpar_tabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(332, 332, 332))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btImprimir)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbContador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_limpar_tabela)
                                .addGap(18, 18, 18)))))
                .addContainerGap())
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(lbContador))
                    .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_limpar_tabela)
                    .addComponent(btPesquisar))
                .addGap(42, 42, 42)
                .addComponent(btImprimir)
                .addGap(48, 48, 48)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuArquivo.setText("Arquivo");
        jMenuBar1.add(MenuArquivo);

        MenuNovo.setText("Novo");
        MenuNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuNovoMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuNovo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_limpar_tabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpar_tabelaActionPerformed
        // TODO add your handling code here:
        control.delete_all(mod);

    }//GEN-LAST:event_bt_limpar_tabelaActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        mod.setPesquisa(btPesquisar.getText());

        CadastroModel model = control.buscaUsuario(mod);

        preencherTabela("SELECT *FROM cadastro WHERE nome like '%"+txtPesquisa.getText() +"%' order by id");
        Contador();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void tableCadastroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableCadastroKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tableCadastroKeyTyped

    private void tableCadastroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableCadastroKeyReleased
        // TODO add your handling code here:
        String id = (String) tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 0);
        System.out.println(id);
        con.conectar();
        con.executeSql("SELECT * FROM cadastro WHERE id="+id);
        try{
            con.rs.first();
            mod.setId(con.rs.getInt("id"));


        } catch(SQLException exception) {
            System.out.println(exception.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao selecionar");
        }

        con.desconectarBanco();


    }//GEN-LAST:event_tableCadastroKeyReleased

    private void tableCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableCadastroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableCadastroKeyPressed

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void tableCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCadastroMouseClicked

        if(evt.getClickCount() >1 ){

            int row = this.tableCadastro.rowAtPoint(evt.getPoint());

            Object obj = (tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 0));
            String id = obj.toString();
            Object obj1 = (tableCadastro.getValueAt(tableCadastro.getSelectedRow(), 1));
            String nome = obj1.toString();

            TelaAterarCadastroView tela1 = new TelaAterarCadastroView();
            tela1.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_tableCadastroMouseClicked

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        try{
            MessageFormat headerFormat = new MessageFormat("Registros de reserva de passageiros");
            MessageFormat footerFormat = new MessageFormat("SysCadastro © 04/2019 - C&N Turismo");

            tableCadastro.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
        }catch (PrinterException e){
            Logger.getLogger(TelaCadastroInicioViewCopia2.class.getName()).log
            (Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btImprimirActionPerformed

    private void MenuNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuNovoMouseClicked
        TelaNovoCadastroView tela = new TelaNovoCadastroView();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuNovoMouseClicked

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"id","nome","telefone","cidade_origem","cidade_destino","data_viagem"};
        con.conectar();
        con.executeSql(Sql);
        try{
            con.rs.first();
            do{
                dados.add(new Object[]{con.rs.getString("id"),con.rs.getString("nome"),con.rs.getString("telefone"),con.rs.getString("cidade_origem"),con.rs.getString("cidade_destino"),con.rs.getString("data_viagem")});
            }while(con.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Registro não encontrado!");
        }
    TabelaCadastroModel modelo = new TabelaCadastroModel(dados, colunas);
    tableCadastro.setModel(modelo);
    
    tableCadastro.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    tableCadastro.getColumnModel().getColumn(0).setMaxWidth(40);
    tableCadastro.getColumnModel().getColumn(1).setMaxWidth(500);
    tableCadastro.getColumnModel().getColumn(2).setMaxWidth(120);
    tableCadastro.getColumnModel().getColumn(3).setMaxWidth(160);
    tableCadastro.getColumnModel().getColumn(4).setMaxWidth(160);
    tableCadastro.getColumnModel().getColumn(5).setMaxWidth(100);
    
    
    tableCadastro.getTableHeader().setReorderingAllowed(true);
    tableCadastro.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    con.desconectarBanco();
    
    }
    
    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroInicioViewCopia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroInicioViewCopia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroInicioViewCopia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroInicioViewCopia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroInicioViewCopia2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuArquivo;
    private javax.swing.JMenu MenuNovo;
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton bt_limpar_tabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbContador;
    private javax.swing.JTable tableCadastro;
    private javax.swing.JLabel txtContador;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

    private void Contador() {
        
        int filas=tableCadastro.getRowCount();
        txtContador.setText(" " + filas);
        
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("bus.png")));
    } 
}